### ISSUE TITLE
dropdown present instead of swatches on product view page

### ISSUE THREAD

**Issue by ghost** [wigman/AjaxSwatches#11]
Another issue I just ran across. On the product view page there are no swatches present, just the dropdowns which still function as they should. Unsure if this is related to the 0.4.1 fix.
## system.log

2015-04-06T23:00:07+00:00 ERR (3): Notice: Undefined offset: 1  in C:\Program Files (x86)\wamp\www\magento\app\code\community\Wigman\AjaxSwatches\Block\Catalog\Product\View\Type\Configurable.php on line 130

**Comment by wigman** [comment]
This was the same bug, but in a different file. Fixed in the latest push, please download the last master version.

**Comment by ghost** [comment]
Dropdown with no swatches still present in 0.4.2. No errors in system log though.

**Comment by wigman** [comment]
Could be that another module (or local override) is interfering with my code. Can't tell without seeing your install or getting a better problem analysis from you.
Try for example to disable all other extensions and app/code/local/Mage overrides and see if the problem continues.
